#!/bin/sh

# script/test: Run the test suite and linters.

set -e

cd "$(dirname "$0")/.."

echo "==      shellcheck"
script/tests/shellcheck

echo "==      gometalinter"
script/tests/gometalinter

echo "==      go-test"
script/tests/go-test "$@"

echo "==      go-test-cover"
script/tests/go-test-cover "$@"

echo "==      go-test-race"
script/tests/go-test-race "$@"
